# Exported from:        http://Jans-MBP.home:5516/
# Release version:      10.0.0-20210203-123974
# Date created:         Thu Mar 11 14:27:57 CET 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata: {}
spec:
- name: scm versioning
  type: xlrelease.FolderVersioningConfig
  scmPath: SCM_PATH_0
- name: jgit connector
  type: git.JGitConnectorConfig
  url: https://github.com/jdolanski/demo_test
  branch: main
  username: jdolanski
  password: !value "git_JGitConnectorConfig_jgit_connector_password"
- template: commit template
  scheduledStartDate: 2021-03-11T09:00:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: do commit
      type: xlrelease.ScriptTask
      taskRecoverOp: SKIP_TASK
      script: "folderId = getCurrentRelease().findFolderId()\nversion = releaseVariables['version']\n\
        tag = folderVersioningApi.createVersion(folderId, version)\nreleaseVariables['createdTag']\
        \ = tag\nresult = True"
    - name: wait
      type: xlrelease.Task
  variables:
  - type: xlrelease.StringVariable
    key: version
  - type: xlrelease.StringVariable
    key: createdTag
    requiresValue: false
    showOnReleaseStart: false
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_commit_template_scriptUserPassword"
  riskProfile: Default risk profile
- template: new template
  scheduledStartDate: 2021-03-11T09:00:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: a
      type: xlrelease.Task
  riskProfile: Default risk profile
